### ISSUE TITLE
Error when running in Visual Studio 2013

### ISSUE THREAD

**Issue by mehdi4467** [tgjones/rasterizr#9]
Dear Sir
When I run this project in visual studio 2013 I get this error.
please see the picture:

http://img5013.photobox.co.uk/06795915b799473a8de27bb890d308f52d4b3d84491371332f40c07f4be1a574f9e5c28f.jpg

**Comment by tgjones** [comment]
You need to make sure the Startup Project is set to `Rasterizr.Studio`.

**Comment by mehdi4467** [comment]
thanks a lot.
its work.
but now I have another problem.
when I run the project below error is appear:
Unable to load DLL 'd3dcompiler_43.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by tgjones** [comment]
You might not have the Direct3D SDK installed.

But that DLL is actually in the lib folder, as part of this repository:
https://github.com/tgjones/rasterizr/tree/master/lib

So you can just copy it to the bin/Debug folder manually, and then it should be found correctly.
